In [11]:
import pandas as pd
data = pd.read_csv("C:/Users/kamok/Downloads/targets - targets.csv")
data

   region_id         region  quarter  target_amount
0          1   Western Cape  2025-Q4          50000
1          2   Eastern Cape  2025-Q4          20000
2          3  Northern Cape  2025-Q4          30000

In [12]:
data = pd.read_csv("C:/Users/kamok/Downloads/Suppliers - Sheet1.csv")
data

   supplier_id  region_id                farm_name
0            1          3        Karoo Lamb Estate
1            2          3     Desert Rose Orchards
2            3          2        Grootfontein Wool
3            4          1  Mountain View Vineyards
4            5          1        Valley Olive Farm
5            6          2        Blue Crane Citrus

In [13]:
data = pd.read_csv("C:\\Users\\kamok\\Downloads\\Orders - Sheet1.csv")
data

    order_id  supplier_id  order_date  total_price
0          1            1  2025-10-05         5200
1          2            2  2025-10-12         8000
2          3            4  2025-10-15        12000
3          4            3  2025-10-20         3500
4          5            5  2025-11-02         9500
5          6            6  2025-11-10         7800
6          7            1  2025-11-15         4500
7          8            2  2025-11-20         9200
8          9            4  2025-12-01        15500
9         10            5  2025-12-10        11000
10        11            3  2025-12-15         4200